# Generated by Django 5.2.4 on 2025-08-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('url', models.URLField(verbose_name='Havola')),
                ('image_url', models.URLField(verbose_name='Rasm havolasi')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('is_send', models.BooleanField(default=False, verbose_name='Yuborilganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
