# Generated by Django 5.2.4 on 2025-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
