# Generated by Django 5.2.4 on 2025-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kanal nomi')),
                ('chat_id', models.BigIntegerField(verbose_name='Kanal ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('is_get_post', models.BooleanField(default=False, verbose_name='Xabar olinsinmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
            },
        ),
    ]
