# Generated by Django 5.2.4 on 2025-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
