# Generated by Django 5.2.4 on 2025-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_channel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kanal nomi')),
                ('chat_id', models.BigIntegerField(verbose_name='Kanal ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('is_send_post', models.BooleanField(default=False, verbose_name='Xabar yuborilsinmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Mening kanalim',
                'verbose_name_plural': 'Mening kanallarim',
            },
        ),
    ]
